# Generated by Django 4.2.5 on 2023-10-09 13:04

from django.db import migrations, models
import foodgram_backend.constants


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=foodgram_backend.constants.UserContant['MAX_USER_NAME_LENGTH'], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=foodgram_backend.constants.UserContant['MAX_USER_NAME_LENGTH'], verbose_name='фамилия'),
        ),
    ]
