# Generated by Django 4.2.5 on 2023-10-08 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Время приготовления не может быть 0'), django.core.validators.MaxValueValidator(10000, 'Время приготовления не может быть таким большим')], verbose_name='Время приготовления'),
        ),
    ]
