# Generated by Django 4.2.5 on 2023-09-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_amountingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
