# Generated by Django 4.2.5 on 2023-10-11 16:40

import django.core.validators
from django.db import migrations, models
import foodgram_backend.constants


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=foodgram_backend.constants.FoodContant['MAX_MEASUREMENT_UNIT_LENGTH'], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(foodgram_backend.constants.FoodContant['MIN_COOKING_TIME'], 'Время приготовления не может быть1'), django.core.validators.MaxValueValidator(foodgram_backend.constants.FoodContant['MAX_COOKING_TIME'], 'Время приготовления не может быть таким большим')], verbose_name='Время приготовления'),
        ),
    ]
