# Generated by Django 4.2.5 on 2023-09-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Ингредиенты в рецепте', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
        migrations.AlterField(
            model_name='quantity',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food.ingredient', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='food.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='quantity',
            constraint=models.UniqueConstraint(fields=('recipe', 'measure'), name='unique_combination'),
        ),
    ]
