# Generated by Django 4.2.5 on 2023-09-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
