# Generated by Django 4.2.5 on 2023-09-19 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_alter_quantity_options_alter_quantity_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
