# Generated by Django 4.2.5 on 2023-09-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='ingredient',
            new_name='name',
        ),
    ]
