# Generated by Django 4.2.5 on 2023-10-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
