# Generated by Django 4.2.5 on 2023-09-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_recipe_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
