# Generated by Django 4.2.5 on 2023-09-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_ingredient_quantity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='name',
            new_name='recipe',
        ),
    ]
