# Generated by Django 4.2.5 on 2023-10-07 19:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#B32428', 'красный'), ('#ffc0cb', 'розовый')], default='красный', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
    ]
