# Generated by Django 4.2.5 on 2023-09-29 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_amountingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0', 'Количество не может быть 0')], verbose_name='Количество'),
        ),
    ]
